// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHKkTQQ0FaBhaRvs8IxLv55Tp9G7CLEYo',
    appId: '1:537876308516:web:95396bffb391b8425b6eb1',
    messagingSenderId: '537876308516',
    projectId: 'loccamb-d1126',
    authDomain: 'loccamb-d1126.firebaseapp.com',
    storageBucket: 'loccamb-d1126.appspot.com',
    measurementId: 'G-QZ9PZG7P1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNDAXVOrR0ZKhqD3WkP6zod9_V9qb34vM',
    appId: '1:537876308516:android:74cb4cba963c05055b6eb1',
    messagingSenderId: '537876308516',
    projectId: 'loccamb-d1126',
    storageBucket: 'loccamb-d1126.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNQmbxZ515gVh6AdUAHel1WZrNxfcZ7xc',
    appId: '1:537876308516:ios:a9115323a0d5efa05b6eb1',
    messagingSenderId: '537876308516',
    projectId: 'loccamb-d1126',
    storageBucket: 'loccamb-d1126.appspot.com',
    iosBundleId: 'com.example.loccamb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNQmbxZ515gVh6AdUAHel1WZrNxfcZ7xc',
    appId: '1:537876308516:ios:a9115323a0d5efa05b6eb1',
    messagingSenderId: '537876308516',
    projectId: 'loccamb-d1126',
    storageBucket: 'loccamb-d1126.appspot.com',
    iosBundleId: 'com.example.loccamb',
  );
}
